--- Asher Macdonald
--- Q1
select USER_ID,
       USERNAME,
       CREATED,
       PASSWORD_CHANGE_DATE
FROM USER_USERS;

--- Q2
SELECT *
FROM USER_TABLES;

--- Q3
DESC ORDERS
DESC PRODUCTLIST
DESC REVIEWS
DESC STOREFRONT
DESC USERBASE
DESC USERLIBRARY

--- Q4
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTLIST;
SELECT * FROM REVIEWS;
SELECT * FROM STOREFRONT;
SELECT * FROM USERBASE;
SELECT * FROM USERLIBRARY;

--- Q5
SELECT table_name,
       constraint_name,
       constraint_type,
       status
FROM USER_CONSTRAINTS;

--- Q6
SELECT VIEW_NAME,
       TEXT
FROM USER_VIEWS;

--- Q7
SELECT USERNAME
FROM ALL_USERS
ORDER BY USERNAME;

--- Q8
SELECT
    firstname,
    lastname,
    username,
    password,
    EMAIL
FROM USERBASE
WHERE EMAIL like '%yahoo%';

---Q9
SELECT USERNAME,
       BIRTHDAY,
       WALLETFUNDS
FROM USERBASE
WHERE WALLETFUNDS < 25;

---Q10
SELECT USERID,
       PRODUCTCODE
FROM USERLIBRARY 
WHERE HOURSPLAYED > 100;

--- Q11
SELECT PRODUCTCODE,
       HOURSPLAYED
FROM USERLIBRARY
WHERE HOURSPLAYED < 10;

---Q12
SELECT DISTINCT PUBLISHER
FROM PRODUCTLIST;

---Q13
SELECT PRODUCTNAME,
       RELEASEDATE,
       PUBLISHER,
       GENRE
FROM PRODUCTLIST
ORDER BY GENRE;

---Q14
SELECT PRODUCTNAME,
       PUBLISHER,
       GENRE
FROM PRODUCTLIST
WHERE GENRE = 'Strategy';

---Q15
SELECT PRODUCTCODE,
       DESCRIPTION,
       PRICE
FROM STOREFRONT
WHERE PRICE > 25
ORDER BY PRICE DESC;

---Q16
SELECT  INVENTORYID,
        PRICE
FROM STOREFRONT
ORDER BY PRICE ASC;

---Q17
SELECT PRODUCTCODE,
       REVIEW,
       RATING
FROM REVIEWS
WHERE RATING = 1;

---Q18
SELECT PRODUCTCODE,
       REVIEW,
       RATING
FROM REVIEWS
WHERE RATING >= 4
ORDER BY RATING ASC;

---Q19
SELECT DISTINCT USERID, ORDERID
FROM ORDERS;

---Q20
SELECT *
FROM ORDERS
ORDER BY PURCHASEDATE ASC;
